Added batch command for linux

diff --git a/.github/workflows/ironpython_linux.yml b/.github/workflows/ironpython_linux.yml
--- a/.github/workflows/ironpython_linux.yml
+++ b/.github/workflows/ironpython_linux.yml
@@ -22,21 +22,15 @@ jobs:
 
       - name: 'Run Unit Tests in Ironpython'
         run: |
-          start-process 'cmd' -ArgumentList '/c .\_unittest_ironpython\run_unittests_batchmode.cmd'
-          $Timeout = 1200
-          while (($Timeout -gt 0) -and (!(Test-Path ".\_unittest_ironpython\tests_succeeded.log")))
-          {
-            Start-Sleep 1
-            $Timeout -= 1
-          }
-          if ( $Timeout  -eq 0)
-          {
-            get-content .\_unittest_ironpython\runner_unittest.log
+          chmod 777 _unittest_ironpython/run_unittests_batchmode_linux.cmd
+          timeout -k 1200s 1200s ./_unittest_ironpython/run_unittests_batchmode_linux.cmd
+          if [ $? -eq 124 ] ; then
+            echo "ERROR: Timeout while waiting for the file _unittest_ironpython/tests_succeeded.log."
             exit 1
-          }
           else
-          {
-            get-content .\_unittest_ironpython\runner_unittest.log
+            cat _unittest_ironpython/runner_unittest.log
             exit 0
-          }
+          fi
+
+
 
